Bugfix/media picker
umbraco/Umbraco.CMS.Backoffice pull request #1399
Opened 2024-03-06 17:42 UTC by JesmoDev

Fixes the image property editor

2024-03-11 12:51 UTC, iOvergaard commented on src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
> +	public value: Array<{ key: string; mediaKey: string; mediaTypeAlias: string }> = [];
Please consider how the migrator converts values from V13 to V14 here. I could fear that it converts these values to a CSV format `key1,key2,key3`. Please verify this before changing the type here.

2024-03-11 13:03 UTC, iOvergaard requested changes

2024-03-11 13:03 UTC, iOvergaard commented on src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
> +		this._items = this.value ? this.value.map((x) => x.mediaKey) : [];
Consider moving this to a _setter_ instead (`public set value()`) which will ensure it happens every time the property is updated and not just when the component itself is updated.

2024-03-11 13:03 UTC, iOvergaard commented on src/packages/media/media/property-editors/image-cropper/property-editor-ui-image-cropper.element.ts
> +			this.value.crops = crops;
Would this not mean that you are overriding any stored crops with the config by doing this? Do crops not also hold references to media items, or are they just simple config objects?

2024-03-12 07:43 UTC, JesmoDev commented on src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
> +				key: UmbId.new(),
I was told that the key is just a unique for that value. And the mediaKey is the unique for the actual media file

2024-03-12 13:12 UTC, iOvergaard approved these changes

2024-03-12 13:12 UTC, merged