move object type files to core
umbraco/Umbraco.CMS.Backoffice pull request #2196
Opened 2024-08-08 12:34 UTC by madsrasmussen

## Description

These files are a leftover from when a relation type was editable from the UI. They aren't used anywhere but they are unfortunately exported. They are currently under "packages" but aren't set up as a package. I have moved them to the core package until they can be deleted. They have their own import map entry so it won't affect imports.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

2024-08-08 16:13 UTC, leekelleher approved these changes

2024-08-08 16:23 UTC, leekelleher requested changes
Sorry, I tested against the wrong branch, (I'd confused with #2195)! 🤦 

I'm getting an error locally and on the GitHub actions...

```
Error: Could not find export: ./object-type -> ./dist-cms/core/object-type/index.js in the build output.
```

I'm unsure what else needs to be changed, as `package.json` looks correct to me.

2024-08-12 07:41 UTC, madsrasmussen commented
@leekelleher Saved by the validate package script 💯 The path to the object-type module was wrong in `package.json`. It was missing the `packages` part.

2024-08-12 17:08 UTC, leekelleher approved these changes
Re-tested, all builds successfully! 🚀

2024-08-12 17:08 UTC, merged