Make Grid List Create Button Respect the Translation of a document type
umbraco/Umbraco.CMS.Backoffice pull request #2435
Opened 2024-10-10 05:48 UTC by IbrahimMNada

This PR is a fix for 
https://github.com/umbraco/Umbraco-CMS/issues/17233#issuecomment-2404068186

This PR simply checks if the document type label starts with '#' which means that the doctype label is translatable
and then removes the '#' and applies the translations 
Before :
<img width="716" alt="image" src="https://github.com/user-attachments/assets/44496468-72f7-4915-bbf1-8592f9b6fa11">

After:
<img width="701" alt="image" src="https://github.com/user-attachments/assets/828e14da-5803-4cb0-8022-784243ee95e9">

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Motivation and context

## How to test?

1-Create a block list for any doc type with translations
2- Go to block type and Check the CreateButtonLabel
3-you will notice that the label is translated

## Screenshots (if appropriate)
Before :
<img width="716" alt="image" src="https://github.com/user-attachments/assets/44496468-72f7-4915-bbf1-8592f9b6fa11">

After:
<img width="701" alt="image" src="https://github.com/user-attachments/assets/828e14da-5803-4cb0-8022-784243ee95e9">

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [x] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
- [] I have added tests to cover my changes.

2024-10-10 07:01 UTC, iOvergaard requested changes
Made a few suggestions to use `string` rather than `term` as that already covers the proposed use case.

2024-10-10 07:01 UTC, iOvergaard commented on src/packages/block/block/workspace/block-workspace-editor.element.ts
> +					this._headline = this.localize.term(isNew ? 'general_add' : 'general_edit') + ' ' +  this.localize.term(name!);
```suggestion
					this._headline = this.localize.term(isNew ? 'general_add' : 'general_edit') + ' ' +  this.localize.string(name!);
```

2024-10-10 07:01 UTC, iOvergaard commented on src/packages/block/block/workspace/views/edit/block-workspace-view-edit.element.ts
> +										>${this.localize.term(tab.name)}</uui-tab
```suggestion
										>${this.localize.string(tab.name)}</uui-tab
```

2024-10-10 07:06 UTC, IbrahimMNada commented
I Will work on them Now

2024-10-10 14:17 UTC, IbrahimMNada commented
changes done and tested all looks good

2024-10-11 07:31 UTC, iOvergaard approved these changes
I have changed the `string` function to accept unknown values, so that it can validate them at runtime. This allows for a better DX experience as you do not have to code defensively on the values passed to it. I have added tests to ensure that this scenario works. I have also fixed a few Sonarcloud issues that arose on unrelated code due to the fact, that it checks changed files only.

2024-10-11 07:32 UTC, merged