property creator
umbraco/Umbraco.CMS.Backoffice pull request #534
Opened 2023-02-21 00:36 UTC by JesmoDev

Adds the property creator with a property settings modal

2023-02-23 08:04 UTC, nielslyngsoe requested changes

2023-03-09 09:49 UTC, madsrasmussen commented on src/core/modal/layouts/property-settings/modal-layout-property-settings.element.ts
> +@customElement('umb-modal-layout-property-settings')
This will be fixed as part of #580

2023-03-09 10:29 UTC, madsrasmussen commented on src/core/modal/layouts/property-settings/modal-layout-property-settings.element.ts
> +			this._alias = this.#generateAlias(this._name);
I have added a todo in the code

2023-03-09 12:21 UTC, nielslyngsoe approved these changes

2023-03-09 12:21 UTC, merged