Remove invalid dot from email and URL validation strings
umbraco/Umbraco.CMS.Backoffice pull request #600
Opened 2023-03-16 12:15 UTC by JasonElkin

## Description

This removes the dot from the default email and URL regexes that can result in bad email addresses/URLs

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Motivation and context

The default validation allows _any_ character (UTF-8, emoji etc.) that are not valid in TLDs - I've seen a few instances of this being missed in the wild (it's been a problem in the Backoffice for a long time).

The old Backoffice actually defines this regex in code like this: `[a-zA-Z0-9_\.\+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-\.]+` but it gets incorrectly transformed by the gulp build into `[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+`, which is wrong.

## How to test?
Create a new property editor, choose email or URL custom validation.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/7151793/225604184-980b3dc5-a940-43ea-8c45-6f85c88ecf07.png)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [x] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

## N.B - this is an opinionated regex!

I appreciate that we want a best-case regex suitable for most users, and no regex is 100% for these kinds of things, but my edge-case spider-sense is tingling 🕷️

### Email addresses
Technically, an email address such as `name@tld` is perfectly valid, and there are TLDs with MX records in the wild ([like guatemala's .gt](https://mxtoolbox.com/SuperTool.aspx?action=mx%3agt&run=toolpage)).

I'd imagine, as when this was first written, that most users would want to make sure that there is a dot in the second part of the email... but maybe we want to take this opportunity to remove that?

### URLs
The previous URL regex does allow for `localhost`, when this is fixed it wont. I'm not sure if that's a problem? I'd imagine that most people validating a URL in the backoffice would want to make sure it's "real", which localhost technically isn't , but I'm not 100% on that.

2023-03-19 10:26 UTC, nul800sebastiaan commented
In my humble opinion: this validation has always had edge-csase complaints over the years, I personally would make it not require a dot after the `@` because that is "more correct". It still doesn't apply to all edge cases though as I recall. 
Maybe we should either have multiple email regex examples in the dropdown, or none and link to docs to pick the most applicable one?

2023-03-20 17:40 UTC, JasonElkin commented
Edge case complaints @nul800sebastiaan? [I can't think what you mean](https://github.com/umbraco/Umbraco-CMS/issues/10404) 😉

I'd personally prefer `[a-zA-Z0-9_.+-]+@[a-zA-Z0-9.-]+`, happy to update.

Not sure about multiple options, how does one signpost the difference in the backoffice?

2023-03-21 01:05 UTC, mikecp commented
What about letters with accents, which are now accepted in emails IIRC 😁😅

2023-03-22 12:28 UTC, iOvergaard commented
> Edge case complaints @nul800sebastiaan? [I can't think what you mean](https://github.com/umbraco/Umbraco-CMS/issues/10404) 😉
> 
> I'd personally prefer `[a-zA-Z0-9_.+-]+@[a-zA-Z0-9.-]+`, happy to update.
> 
> Not sure about multiple options, how does one signpost the difference in the backoffice?

I agree with your suggestion, @JasonElkin. Let's simplify the regex to match the RFC for emails more closely. This version of the backoffice will land in a major version and thus be appropriate to introduce a potential breaking change 😇

Would you update your PR?

2023-03-29 14:05 UTC, iOvergaard requested changes
Changes requested

2023-04-20 10:14 UTC, iOvergaard approved these changes
Will merge this. I think it's fine for now having a more complex email regex, since it's meant to help the user type a "valid" public email.

2023-04-20 10:14 UTC, merged