Markdown keybindings and img tags
umbraco/Umbraco.CMS.Backoffice pull request #943
Opened 2023-10-24 13:29 UTC by loivsen

## Description

**Markdown editor**
- Adjustments to the keybindings. Changing the keybindings to resemble the Github Markdown keybindings.
- Action buttons title tooltip now also contains the keybindings.
- Fixed the sanitizeHtml to not remove IMG tags.
- Styling of preview when inserting inline code, code block, & horizontal lines.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

2023-11-03 10:09 UTC, iOvergaard approved these changes

2023-11-03 10:11 UTC, iOvergaard commented
@loivsen Looks good, but it needs to be updated for DOMPurify which we are using now, since sanitize-html didn't work as expected in the build :)

2023-11-03 10:11 UTC, iOvergaard requested changes
@loivsen Looks good, but it needs to be updated for DOMPurify which we are using now, since sanitize-html didn't work as expected in the build :)

2023-11-07 14:26 UTC, nielslyngsoe approved these changes

2023-11-08 13:06 UTC, iOvergaard approved these changes
LGTM

2023-11-08 13:17 UTC, merged